name: Test

on:
  push:
    branches-ignore:
    - master

env:
  LOG_LEVELS: fatal
  NODE_VERSION: 12.13.1
  TLS_UNPROTECTED: world

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019]

    runs-on: ${{ matrix.os }}

    services:
      mongo:
        image: mongo:3.6.17
        ports:
        - 27017:27017
      consul:
        image: consul:0.9.3
        ports:
        - 8500:8500

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        NODE_VERSION: ${{ env.NODE_VERSION }}

    - name: Cache Node.js modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run bot
